### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by hanserasmus** [nextcloud/stt_helper#10]
Hi

Thank you for this app. 

I have installed the Whisper app in Nextcloud as well, and it is functioning. However, I have uploaded an audio file to Nextcloud and want to test transcription of it. I am not able to. Where exactly do I select the files I want to transcribe? There is no "app" in the app ribbon at the top, nor is there any context menu option when clicking on the three dots next to the file.

Also in my admin settings I see this:

![image](https://github.com/nextcloud/stt_helper/assets/24249616/e299a290-14ce-4e2f-aad3-6e3a6ed31967)

**Comment by kyteinsky** [comment]
Hello,  
This app is a smart picker provider that can be accessed from multiple applications like Text and Talk by pressing `/` in a text field/area and choosing "Speech to Text" option. More info on smart pickers can be found here: https://docs.nextcloud.com/server/latest/admin_manual/reference/smart_picker.html#where-can-it-be-used

**Comment by hanserasmus** [comment]
Thank you for the clarification @kyteinsky . So this app cannot be used to invoke a transcription of a complete audio file uploaded to Nextcloud? Because that is what I am trying to achieve.

**Comment by kyteinsky** [comment]
It can be. It just needs to be done through the smart picker.  
When you select the option of "Speech to Text" in the smart picker menu, it will open up a dialog that does exactly that.

**Comment by hanserasmus** [comment]
Thank you. I found the smart picker through the `Open details > Activity` column in the `Files` view.
